# Generated by Django 4.1.7 on 2023-04-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=11, verbose_name='Номер автомобиля')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='x_relative',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CarRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_action', models.CharField(max_length=20, verbose_name='Название действия')),
                ('date', models.DateTimeField(verbose_name='Время')),
                ('image', models.ImageField(upload_to='carRegister/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carRegister.whitelist')),
            ],
        ),
    ]
