# Generated by Django 4.1.7 on 2023-03-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='x_relative',
            field=models.FloatField(default=0.0),
        ),
    ]
