# Generated by Django 4.2.1 on 2023-06-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0002_whitelist_point_x_relative_carregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='name',
            field=models.CharField(default='User', max_length=50, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='carregister',
            name='employee',
            field=models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to='carRegister.whitelist'),
        ),
    ]
