# Generated by Django 4.1.7 on 2023-03-29 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0002_point_x_relative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150, verbose_name='ФИО')),
                ('car_number', models.CharField(max_length=11, verbose_name='Номер автомобиля')),
                ('job', models.CharField(max_length=50, verbose_name='Должность')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('car_mark', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('car_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1930)], verbose_name='Год выпуска автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_action', models.CharField(max_length=20, verbose_name='Название действия')),
                ('date', models.DateTimeField(verbose_name='Время')),
                ('image', models.ImageField(upload_to='carRegister/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRegister.employee')),
            ],
        ),
    ]
