# Generated by Django 4.1.7 on 2023-04-02 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0003_employee_carregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=11, verbose_name='Номер автомобиля')),
                ('car_mark', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('car_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1930)], verbose_name='Год выпуска автомобиля')),
            ],
        ),
        migrations.AlterField(
            model_name='carregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRegister.whitelist'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
