# Generated by Django 4.2.1 on 2023-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRegister', '0004_alter_carregister_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
